### PR TITLE
Issue fixes in VO

### LINKED ISSUE #44: Parallel view : Screen size limit -Book and chapter does not display alongside the selected language for languages with long string length
Issue description : On selecting a new language in the parallel view , the book and chapter does not display alongside the selected language for languages with long string length. (Malayalam, Deuteronomy, Nagamese, etc)
Steps:
Select a language and book (say Hindi IRV and यहोशू 20)
Now select parallel view and  select a language with long string such as Malayalam 
Observation:
Along with the selected language, the book  name and chapter does not display 
Expected : The code is to be enhanced to include a wider set of screen size resolution  such that the book and chapter name are displayed alongside the selected book 
Missing book and chapter name in parallel bible view

### PR DESCRIPTION
**Pull request by AnuMonachan**
Minor issues related to parallel view, next/previous chapters and empty commentaries fixed
#44 
#68

### CODE REVIEW

File: src/components/read/MenuBar.js [hunk 1]
```diff
@@ -17,9 +17,17 @@ import { BLUETRANSPARENT } from "../../store/colorCode";
 import Close from "../common/Close";
 
 const useStyles = makeStyles((theme) => ({
+  root: {
```
Comment (RevantCI) [inline src/components/read/MenuBar.js:20]: Do we need this class root? 
Tried removing it and it didn't seem to have any effect, are we covering some special case with it?

File: src/components/read/MenuBar.js [hunk 2]
```diff
@@ -17,9 +17,17 @@ import { BLUETRANSPARENT } from "../../store/colorCode";
...
+    width: "100%",
+    marginTop: 82,
+  },
+
   read: {
-    padding: "0 10px 0 44px",
+    marginBottom: 20,
```
Comment (RevantCI) [inline src/components/read/MenuBar.js:26]: Do we need marginBottom and float, tried removeing them also and they did not seem to have any effect, if they're not needed we can remove them.

**Review by RevantCI — APPROVED** [review]

File: src/components/stories/Stories.js [hunk 3]
```diff
@@ -110,11 +120,19 @@ const Stories = (props) => {
...
     event.preventDefault();
+
     let storyNum = event.currentTarget.getAttribute("data-id");
     if (storyNum.length < 2) storyNum = "0" + storyNum;
     setStoryId(storyNum);
   };
 
+  const storySetter = (event) => {
+    let storyNum = event.target.value;
+    console.log(storyNum);
```
Comment (RevantCI) [inline src/components/stories/Stories.js:131]: This can be removed

File: src/components/stories/Stories.js [hunk 4]
```diff
@@ -151,31 +169,44 @@ const Stories = (props) => {
...
-                    {languageJson[text]}
-                  </MenuItem>
-                ))}
-              </Select>
-            </FormControl>
-            <div>
+        {mobile === true ? (
+          <Box className={classes.mobile} p={1}>
+            <Box p={1} flexGrow={1}>
+              <FormControl variant="outlined" style={{ minWidth: 100 }}>
```
Comment (RevantCI) [inline src/components/stories/Stories.js:175]: The language combo can be put in a function or state variable and reused,
Also the settings menu can be put in a function or state variable and reused

File: src/components/stories/Stories.js [hunk 5]
```diff
@@ -151,31 +169,44 @@ const Stories = (props) => {
...
+                  {languages.map((text, y) => (
+                    <MenuItem key={y} value={text}>
+                      {languageJson[text]}
+                    </MenuItem>
+                  ))}
+                </Select>
+              </FormControl>
+              <FormControl
+                variant="outlined"
+                style={{ marginLeft: 20, maxWidth: "40%" }}
```
Comment (RevantCI) [inline src/components/stories/Stories.js:186]: We can increase this to 50%

File: src/components/stories/Stories.js [hunk 6]
```diff
@@ -151,31 +169,44 @@ const Stories = (props) => {
...
-                  <MenuItem key={y} value={text}>
-                    {languageJson[text]}
-                  </MenuItem>
-                ))}
-              </Select>
-            </FormControl>
-            <div>
+        {mobile === true ? (
+          <Box className={classes.mobile} p={1}>
+            <Box p={1} flexGrow={1}>
```
Comment (RevantCI) [inline src/components/stories/Stories.js:174]: In the Box outside the language and story drop down we can put a maxwidth of 90% as the settings menu sometimes gets hidden if the story name is large

File: src/components/read/TopBar.js [hunk 7]
```diff
@@ -108,12 +107,18 @@ const useStyles = makeStyles((theme) => ({
     "&:hover": {
       color: "inherit",
     },
+    [theme.breakpoints.only("xs")]: {
```
Comment (RevantCI) [inline src/components/read/TopBar.js:110]: change to .down("sm")

File: src/components/read/TopBar.js [hunk 8]
```diff
@@ -108,12 +107,18 @@ const useStyles = makeStyles((theme) => ({
...
+      display: "none",
+    },
   },
 }));
 
 export default function TopBar({ login, userDetails }) {
   const classes = useStyles();
   const [loginButton, setLoginButton] = React.useState();
+  const theme = useTheme();
+  const mobile = useMediaQuery(theme.breakpoints.down("sm"));
```
Comment (RevantCI) [inline src/components/read/TopBar.js:120]: change to xs

File: src/components/read/TopBar.js [hunk 9]
```diff
@@ -144,10 +144,9 @@ export default function TopBar({ login, userDetails }) {
               target="_blank"
               rel="noopener"
             >
-              Back to classic site
+              {mobile === true ? "Classic" : "Back to classic site"}
```
Comment (RevantCI) [inline src/components/read/TopBar.js:147]: Not needed as we are hiding it in sm down earlier

Comment (RevantCI) [reply src/components/read/TopBar.js:147]: So a small change in UI attaching screenshots here. Desktop View (md and above)
image
Tablet View, ie only sm
image
Mobile view ie only xs
image
You can use the same UI  in the other 2 screens also 
Sorry about this change, saw that in the tablet view there was some space we could use in the header.
you can generate a fresh pr for this.

Comment (RevantCI) [reply src/components/read/TopBar.js:147]: Hi Anu you can use this logic for the landing page and study bible page header also.

File: src/components/stories/Stories.js [hunk 10]
```diff
@@ -151,31 +169,44 @@ const Stories = (props) => {
...
-                {languages.map((text, y) => (
-                  <MenuItem key={y} value={text}>
-                    {languageJson[text]}
-                  </MenuItem>
-                ))}
-              </Select>
-            </FormControl>
-            <div>
+        {mobile === true ? (
+          <Box className={classes.mobile} p={1}>
```
Comment (RevantCI) [inline src/components/stories/Stories.js:173]: See if you can make the mobile (langauge and story selector ) header sticky, you can try css position:sticky 
https://www.w3schools.com/howto/howto_css_sticky_element.asp
You may need to put backgroundColor as white also
