### PR TITLE
Book dropdown Issue fixed for minority lang #400

### LINKED ISSUE #400: Show bible videos if bible is not present for language
Some new bible video content has come up in minority languages, need to ensure that these languages which don't have bibles are showing up properly in the website as the original use case we had did not cover the case when that languages bible is not present.
Once the content team creates the video csv and it is added to staging appropriate code changes need to be done to ensure it is shown properly.
The bible book names would also be needed as the book drop down has to be populated ( if not available we can use English as a fall back)
image

The new minority languages are, ( mostly Luke videos)

1. Churahi 
2. Gaddi 
3. Kangri 
4. Pahari Kullu
5. Mandeali 
6. Pahari Mahasu 

Related Vachan Content issue - https://github.com/Bridgeconn/vachancontentrepository/issues/183

### PR DESCRIPTION
**Pull request by Beenamol**
In mobile browser , after selecting the minority language , not able to change the book from the book dropdown - issue fixed #400

### CODE REVIEW

File: src/components/video/Video.js [hunk 1]
```diff
@@ -152,6 +155,26 @@ const Video = (props) => {
...
+      const vBook = bibleBooks.find((l) => l?.abbreviation === vBookCode[0]);
+      let vBookArr = [];
+      let obj1 = {
+        abbr: vBook.abbreviation,
+        book_code: vBook.abbreviation,
+        book_id: vBook.bookId,
+        long: vBook.book,
+        short: vBook.book,
+      };
+      vBookArr.push(obj1);
```
Comment (RevantCI) [inline src/components/video/Video.js:172]: This will only work for single book 
Can you try to put this block in a loop like bibleBooks.forEach()

**Review by RevantCI — CHANGES_REQUESTED** [review]

**Review by RevantCI — APPROVED** [review]
